---
# generic settings
main_username: hodgesd
main_groupname: "{{ main_username }}"
main_uid: "501"
main_gid: "{{ main_uid }}"

# ferrarimarco.bash-aliases
bash_aliases:
  - alias: c
    command: clear
  - alias: e
    command: exit

# weareinteractive.environment
environment_config: { "PUID": "{{ main_gid }}", "PGID": "{{ main_gid }}" }
# geerlingguy.ntp
ntp_timezone: "America/Chicago"

# geerlingguy.security
security_ssh_port: 22
security_ssh_password_authentication: "no"
security_ssh_permit_root_login: "no"
security_ssh_usedns: "no"
security_autoupdate_enabled: true
security_fail2ban_enabled: true
security_sudoers_passwordless:
  - hodgesd

# geerlingguy.docker
docker_compose_version: 1.29.2

# geerlingguy.pip
pip_package: python3-pip
pip_executable: pip3

# ironicbadger.docker_compose_generator
appdata_path: /opt/appdata
global_env_vars:
  - "PUID={{ main_uid }}"
  - "PGID={{ main_gid }}"
  - "TZ={{ ntp_timezone }}"
docker_compose_generator_uid: "{{ main_uid }}"
docker_compose_generator_gid: "{{ main_gid }}"
docker_compose_generator_output_path: /Users/hodgesd/config
