---
# generic settings
main_username: derrickhodges
main_groupname: "{{ main_username }}"
main_uid: "501"
main_gid: "{{ main_uid }}"

# ferrarimarco.bash-aliases
bash_aliases:
  - { alias: "dtail", command: "docker logs -tf --tail='50' " }
  - { alias: "dstop", command: "docker stop `docker ps -aq`" }
  - { alias: "drm", command: "docker rm `docker ps -aq`" }
  - { alias: "dcp", command: "docker-compose -f ~/docker-compose.yml " }
  - {
      alias: "dcporph",
      command: "docker-compose -f ~/docker-compose.yml --remove-orphans ",
    }
  - { alias: "dprune", command: "docker image prune" }
  - { alias: "dprunesys", command: "docker system prune --all" }
  - {
      alias: "bashreload",
      command: "source ~/.bashrc && echo Bash config reloaded;",
    }
  - {
      alias: "ctop",
      command: "docker run --name ctop  -it --rm -v /var/run/docker.sock:/var/run/docker.sock http://quay.io/vektorlab/ctop ",
    }
  - {
      alias: "sshclear",
      command: "rm ~/.ssh/multiplex/* -f && echo SSH connection cache cleared;",
    }
  - {
      alias: "sshlist",
      command: "echo Currently open ssh connections && echo && l ~/.ssh/multiplex/",
    }
  - {
      alias: "dfclean",
      command: "df -h -x tmpfs -x zfs -t fuse.mergerfs -t xfs -t ext4",
    }
  - {
      alias: "dfzfs",
      command: "df -h -x tmpfs -t fuse.mergerfs -t xfs -t ext4 -t zfs",
    }

# weareinteractive.environment
environment_config: { "PUID": "{{ main_gid }}", "PGID": "{{ main_gid }}" }
# geerlingguy.ntp
ntp_timezone: "America/Chicago"

# geerlingguy.security
security_ssh_port: 22
security_ssh_password_authentication: "no"
security_ssh_permit_root_login: "no"
security_ssh_usedns: "no"
security_autoupdate_enabled: true
security_fail2ban_enabled: true
security_sudoers_passwordless:
  - derrickhodges

# geerlingguy.docker
docker_compose_version: 1.29.2

# geerlingguy.pip
pip_package: python3-pip
pip_executable: pip3

# ironicbadger.docker_compose_generator
appdata_path: /opt/appdata
global_env_vars:
  - "PUID={{ main_uid }}"
  - "PGID={{ main_gid }}"
  - "TZ={{ ntp_timezone }}"
docker_compose_generator_uid: "{{ main_uid }}"
docker_compose_generator_gid: "{{ main_gid }}"
docker_compose_generator_output_path: /Users/derrickhodges/config
