---
ntp_timezone: America/Chicago

# ironicbadger.docker_compose_generator
global_env_vars:
  - "PUID=501"
  - "PGID=20"
appdata_path: /Users/hodgesd/config
docker_compose_generator_output_path: /Users/hodgesd/code/ansible/infra

containers:
  - service_name: nginxtest
    active: true
    image: nginx
    ports:
      - "80:80"
    restart: unless-stopped
  - service_name: nginxtest2
    active: true
    image: nginx
    ports:
      - "804:80"
    restart: unless-stopped
  - service_name: portainer
    active: true
    image: portainer/portainer-ce
    ports:
      - "9000:9000"
      - "8000:8000"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - "{{ appdata_path }}portainer/data:/data"
    restart_policy: always
  - service_name: librespeed
    active: true
    image: adolfintel/speedtest
    ports:
      - 8008:80
    environment:
      - MODE=standalone
      - TELEMETRY=true
      - PASSWORD=tulanite
    restart: unless-stopped
  - service_name: nextcloud
    active: true
    image: lscr.io/linuxserver/nextcloud:latest
    environment:
      - PUID="{{ PUID }}"
      - PGID="{{ PGID }}"
      - TZ="{{ ntp_timezone }}"
    volumes:
      - "{{ appdata_path }}nextcloud/config:/config"
      - "{{ appdata_path }}/nextcloud/data:/data"
    ports:
      - 443:443
    restart: unless-stopped
  - service_name: plex
    active: true
    image: linuxserver/plex:1.27.2
    restart: unless-stopped
