roles:
  - name: elliotweiser.osx-command-line-tools
#  - name: ironicbadger.docker_compose_generator
#  - name: ironicbadger.bash_aliases
#  - name: fastparrot.yourls
#  - name: geerlingguy.docker
#  - name: geerlingguy.pip
#  - name: geerlingguy.security
#  - name: gantsign.oh-my-zsh

collections:
  - name: geerlingguy.mac