roles:
  - src: ironicbadger.docker_compose_generator
  - src: ironicbadger.bash_aliases
  - src: fastparrot.yourls
  - src: geerlingguy.docker
  - src: geerlingguy.pip
  - src: geerlingguy.security
collections:
  - name: community.docker
