---
- hosts: marauder
  vars_files:
    - "vars/vault.yaml"
  roles:
    - role: ironicbadger.docker_compose_generator
      tags: compose
    # - role: fastparrot.yourls

  tasks:
    - name: Deploy Containters
      community.docker.docker_compose:
        project_src: "{{ docker_compose_generator_output_path }}"
        state: present

- hosts: docker_host
  vars_files:
    - "vars/vault.yaml"
  roles:
    - role: geerlingguy.security
    - role: geerlingguy.docker
    - role: geerlingguy.pip
    - role: ironicbadger.docker_compose_generator
      tags: compose

  tasks:
    - name: Install docker-compose python package
      ansible.builtin.pip:
        name: docker-compose
    - name: Deploy Containters
      tags: compose
      community.docker.docker_compose:
        project_src: "{{ docker_compose_generator_output_path }}"
        state: present
